### ISSUE TITLE
ECMAScript Version of DXQueue error

### ISSUE THREAD

**Issue by belaie** [lhaeger/dxqueue#3]
Input was <modify> xds
driver dn tried:  LDAP and slashed version

Documentation of ECMAScript version is missing too

12/25/20 17:40:51.612]:QueueEvent PT:          Action: do-set-local-variable("local.sub.etp.Schedule",scope="policy",token-xpath("es:sendQueueEvent($DriverDN, $Xds)")).
[12/25/20 17:40:51.614]:QueueEvent PT:            arg-string(token-xpath("es:sendQueueEvent($DriverDN, $Xds)"))
[12/25/20 17:40:51.616]:QueueEvent PT:              token-xpath("es:sendQueueEvent($DriverDN, $Xds)")
[12/25/20 17:40:51.625]:QueueEvent PT:                sendQueueEvent: : Cleaning up supplied XDS
[12/25/20 17:40:51.625]:QueueEvent PT:                sendQueueEvent: : Creating skeleton using context: input
[12/25/20 17:40:51.630]:QueueEvent PT:
DirXML Log Event -------------------
     Driver:   DriverSet\QueueEvent
     Channel:  Publisher
     Status:   Error
     Message:  Code(-9131) Error in vnd.nds.stream:IDM/DriverSet/QueueEvent/0-pub-itp-QueueEventSchedule#XmlData:58 : Error evaluating XPATH expression 'token-xpath("es:sendQueueEvent($DriverDN, $Xds)")' : com.novell.xml.xpath.XPathEvaluationException: Can't find method com.novell.nds.dirxml.engine.NdsDtd.createStatusDocument(java.lang.Integer,com.novell.soa.script.mozilla.javascript.Undefined,com.novell.soa.script.mozilla.javascript.ConsString). (vnd.nds.stream:///lib-ecma-DXQueue#DirXML-Data#227).
[12/25/20 17:40:51.652]:QueueEvent PT:
<nds dtdversion="4.0" ndsversion="8.x">
  <source>
    <product edition="Advanced" version="4.7.4.0">DirXML</product>
    <contact>NetIQ Corporation</contact>
  </source>
  <output>
    <status level="error">Code(-9131) Error in vnd.nds.stream:///DriverSet/QueueEvent/0-pub-itp-QueueEventSchedule#XmlData:58 : Error evaluating XPATH expression 'token-xpath("es:sendQueueEvent($DriverDN, $Xds)")' : com.novell.xml.xpath.XPathEvaluationException: Can't find method com.novell.nds.dirxml.engine.NdsDtd.createStatusDocument(java.lang.Integer,com.novell.soa.script.mozilla.javascript.Undefined,com.novell.soa.script.mozilla.javascript.ConsString). (vnd.nds.stream:///lib-ecma-DXQueue#DirXML-Data#227).<application>DirXML</application>
      <module>QueueEvent</module>
      <object-dn></object-dn>
      <component>Publisher</component>
    </status>
  </output>
</nds>

**Comment by Olethros** [comment]
I have pushed a new version of the sendQueueEvent which should fix this. (the fix is on my repo for now)
It simplifies a few things to avoid the issue above.

Doc is on the way, but the two implementations should be primarily drop-in replacements for each other.
